# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [6]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [35]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [36]:
np.__version__

np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-b3ecbnku/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-b3ecbnku/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.31.188.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.31.188.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-b3ecbnku/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-b3ecbnku/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas config

#### 3. Create a null vector of size 10 (★☆☆)

vector = np.zeros(10)

In [37]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [38]:
vector = np.zeros(10)
print("%d bytes" %vector.nbytes)
# vector name of the array which we want to check memory size

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [39]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> n

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [40]:
arr = np.zeros(9)
arr1 = np.insert(arr,4,1,)
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [41]:
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [42]:
arr = np.arange(1,11)
rev = arr[::-1]
print(f"The array : {arr}")
print(f"The reverse of array : {rev}")

The array : [ 1  2  3  4  5  6  7  8  9 10]
The reverse of array : [10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [43]:
matrix = np.arange(0,9)
matrix_3X3 = matrix.reshape(3,3)
print(matrix_3X3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [44]:
arr = np.array([1,2,0,0,4,0])
# index = 0
# for i in arr :
#     if i > 0 :
#         print(f"{i} index : {index}")
#     index += 1
print(np.nonzero(arr))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [45]:
identity_mat = np.eye(3,3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
import numpy as np
Random_matrix = np.random.random((3,3,3)) # random give random value
# Where the second random is the function like randint
print(Random_matrix)

[[[0.74915927 0.66603189 0.72760081]
  [0.96335718 0.8760967  0.98409931]
  [0.93588616 0.83455376 0.55586386]]

 [[0.62078377 0.60715437 0.92613432]
  [0.20541562 0.02712281 0.68342939]
  [0.84659345 0.08064367 0.5514848 ]]

 [[0.80895096 0.89662084 0.78450046]
  [0.59470471 0.80431346 0.98277154]
  [0.87246006 0.96133178 0.97356969]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [47]:
# random_array = np.random.random((10,10))
random_array = np.random.randint(0,50,(10,10))
min_value = random_array.min()
max_value = random_array.max()

print(random_array)
print(f"The minimum value in the random matrix is : {min_value}")
print(f"The maximum value in the random matrix is : {max_value}")

[[44  1  5  5  3 40 33 36  5 26]
 [17  6 45 39 46 44 43 26 18 38]
 [31 42 27 19 22 44  1 40 45 17]
 [35 20 40 10  1 35 11  2 20 47]
 [14  1 17 24 25  4 21 44 11  2]
 [16 46  7 27 19 18 25 10  8 42]
 [ 9 11 11 34 31 21 30 35 44 14]
 [42 28 46 46 28 30 36  1 25 33]
 [29 13 32 12 46 11  6  3 31 28]
 [26 47 23 27 17 13 21 32  4 40]]
The minimum value in the random matrix is : 1
The maximum value in the random matrix is : 47


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [138]:
vector_random = np.random.randint(1,100,(30))
print(vector_random)
print(vector_random.mean())

[23 19 25 55 40 19 86 97 58 63 53 23 39 98 10 69 97 93 27 72 28 99 43 77
 31 90 22  1 92 39]
52.93333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [56]:
matrix1 = np.ones((4,4))
matrix1[1:-1,1:-1] = 0
print(matrix1)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [69]:
matrix_ran = np.random.randint(1,45,(3,3))
border_zero_arr = np.pad(matrix_ran,(1,1), mode="constant", constant_values=0)
print(border_zero_arr)
# without constant_values it takes by default 0

[[ 0  0  0  0  0]
 [ 0 18 20 33  0]
 [ 0 24 29  5  0]
 [ 0 19 41 21  0]
 [ 0  0  0  0  0]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [81]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [107]:
'''
matrix_5X5 = np.eye(5,5)
matrix_5X5[1,0]=1
matrix_5X5[2,1]=2
matrix_5X5[3,2]=3
matrix_5X5[4,3]=4
print(matrix_5X5)
'''
matrix_2 = np.diag(1+np.arange(4), k=-1) # k is digonal index value 
# for below the digonal using -1
print(matrix_2)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [121]:
matrix = np.zeros((8,8))
matrix[::2,::2] = 1
matrix[1::2,1::2] = 1
print(matrix)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [130]:
print(np.unravel_index(99, (6,7,8)))
# print(np.unravel_index.__doc__)
# (1,5,3) = index of 100th element

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [7]:
import numpy as np

zero_one_arr = np.array([[1,0,],[0,1]])
checkerboard_marix = np.tile(zero_one_arr, (4,4))
print(checkerboard_marix)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [15]:
ran_matrix = np.random.randint(1,50,(5,5))
print(ran_matrix)
mean = ran_matrix.mean()
std = ran_matrix.std()
normalized = (ran_matrix - mean) / std
print('\nThe normalized matrix : \n')
print(normalized)

[[ 3 31 10 22  9]
 [48 41 27 30 19]
 [44 12  9 13  3]
 [44 22  6 32 40]
 [20 37 11 43 46]]

The normalized matrix : 

[[-1.48755586  0.41608052 -1.01164677 -0.1958026  -1.07963378]
 [ 1.57185976  1.09595066  0.14413247  0.34809351 -0.39976364]
 [ 1.29991171 -0.87567274 -1.07963378 -0.80768572 -1.48755586]
 [ 1.29991171 -0.1958026  -1.28359482  0.48406754  1.02796365]
 [-0.33177663  0.82400261 -0.94365975  1.23192469  1.43588573]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
arr = np.array([(1,0,34,2),(2,34,56,67),(3,45,34,7),(4,255,34,56)], dtype=color)
print(arr)

[(1,   0, 34,  2) (2,  34, 56, 67) (3,  45, 34,  7) (4, 255, 34, 56)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [46]:
multiply_of_matrix = np.matmul(np.random.randint(1,100,(5,3)),np.random.randint(1,100,(3,2)))
print(multiply_of_matrix)

[[10322  7776]
 [10096 13848]
 [ 4741  8332]
 [ 8368  9071]
 [ 5608  5110]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
sample_arr = np.array([1,2,3,4,5,6,7,8,9,10,8,3,4,5,6,1])
mat_1 = sample_arr[sample_arr<=8] # elements less than equal to 8
mat_2 = mat_1[mat_1>=3] # elements greater than equal to 3
print(mat_2)

[3 4 5 6 7 8 8 3 4 5 6]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [68]:
print(sum(range(5),-1)) # O/P => 9 
# [0 1 2 3 4] => -1+(4+3+2+1+0) = 9 , -1 is the starting index
# in default case the index is 0 therefore 0+(4+3+2+1+0) = 10 ✅
from numpy import *
print(sum(range(5),-1)) # 10 

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [9]:
import numpy as np
Z = np.array([1,2,3,4,5,6])
print(Z*Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) not legal

[ 1  4  9 16 25 36]
[ 1  2  4  8 16 32]
[False False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j]
[1. 2. 3. 4. 5. 6.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [10]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Admin\AppData\Local\Temp\ipykernel_21212\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Admin\AppData\Local\Temp\ipykernel_21212\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Admin\AppData\Local\Temp\ipykernel_21212\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

hint: np.uniform, np.copysign, np.ceil, np.abs, np.where


#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)